/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedProfileIndexRouteImport } from './routes/_authenticated/profile.index'
import { Route as AuthenticatedUpgradeCallbackRouteImport } from './routes/_authenticated/upgrade.callback'
import { Route as AuthenticatedProfileSupportRouteImport } from './routes/_authenticated/profile.support'
import { Route as AuthenticatedProfilePrivacyRouteImport } from './routes/_authenticated/profile.privacy'
import { Route as AuthenticatedProfilePersonalRouteImport } from './routes/_authenticated/profile.personal'
import { Route as AuthenticatedProfileFeedbackRouteImport } from './routes/_authenticated/profile.feedback'
import { Route as AuthenticatedProfileAboutRouteImport } from './routes/_authenticated/profile.about'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated/admin.payments'
import { Route as AuthenticatedAdminNovaHubRouteImport } from './routes/_authenticated/admin.nova-hub'
import { Route as ApiPublicPaystackWebhookRouteImport } from './routes/api/public/paystack/webhook'
import { Route as ApiPublicNovahubWebhookRouteImport } from './routes/api/public/novahub/webhook'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileIndexRoute =
  AuthenticatedProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUpgradeCallbackRoute =
  AuthenticatedUpgradeCallbackRouteImport.update({
    id: '/upgrade/callback',
    path: '/upgrade/callback',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileSupportRoute =
  AuthenticatedProfileSupportRouteImport.update({
    id: '/profile/support',
    path: '/profile/support',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfilePrivacyRoute =
  AuthenticatedProfilePrivacyRouteImport.update({
    id: '/profile/privacy',
    path: '/profile/privacy',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfilePersonalRoute =
  AuthenticatedProfilePersonalRouteImport.update({
    id: '/profile/personal',
    path: '/profile/personal',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileFeedbackRoute =
  AuthenticatedProfileFeedbackRouteImport.update({
    id: '/profile/feedback',
    path: '/profile/feedback',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileAboutRoute =
  AuthenticatedProfileAboutRouteImport.update({
    id: '/profile/about',
    path: '/profile/about',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/admin/payments',
    path: '/admin/payments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminNovaHubRoute =
  AuthenticatedAdminNovaHubRouteImport.update({
    id: '/admin/nova-hub',
    path: '/admin/nova-hub',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicPaystackWebhookRoute =
  ApiPublicPaystackWebhookRouteImport.update({
    id: '/api/public/paystack/webhook',
    path: '/api/public/paystack/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicNovahubWebhookRoute = ApiPublicNovahubWebhookRouteImport.update({
  id: '/api/public/novahub/webhook',
  path: '/api/public/novahub/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/nova-hub': typeof AuthenticatedAdminNovaHubRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/profile/about': typeof AuthenticatedProfileAboutRoute
  '/profile/feedback': typeof AuthenticatedProfileFeedbackRoute
  '/profile/personal': typeof AuthenticatedProfilePersonalRoute
  '/profile/privacy': typeof AuthenticatedProfilePrivacyRoute
  '/profile/support': typeof AuthenticatedProfileSupportRoute
  '/upgrade/callback': typeof AuthenticatedUpgradeCallbackRoute
  '/profile/': typeof AuthenticatedProfileIndexRoute
  '/api/public/novahub/webhook': typeof ApiPublicNovahubWebhookRoute
  '/api/public/paystack/webhook': typeof ApiPublicPaystackWebhookRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/nova-hub': typeof AuthenticatedAdminNovaHubRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/profile/about': typeof AuthenticatedProfileAboutRoute
  '/profile/feedback': typeof AuthenticatedProfileFeedbackRoute
  '/profile/personal': typeof AuthenticatedProfilePersonalRoute
  '/profile/privacy': typeof AuthenticatedProfilePrivacyRoute
  '/profile/support': typeof AuthenticatedProfileSupportRoute
  '/upgrade/callback': typeof AuthenticatedUpgradeCallbackRoute
  '/profile': typeof AuthenticatedProfileIndexRoute
  '/api/public/novahub/webhook': typeof ApiPublicNovahubWebhookRoute
  '/api/public/paystack/webhook': typeof ApiPublicPaystackWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/nova-hub': typeof AuthenticatedAdminNovaHubRoute
  '/_authenticated/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/_authenticated/profile/about': typeof AuthenticatedProfileAboutRoute
  '/_authenticated/profile/feedback': typeof AuthenticatedProfileFeedbackRoute
  '/_authenticated/profile/personal': typeof AuthenticatedProfilePersonalRoute
  '/_authenticated/profile/privacy': typeof AuthenticatedProfilePrivacyRoute
  '/_authenticated/profile/support': typeof AuthenticatedProfileSupportRoute
  '/_authenticated/upgrade/callback': typeof AuthenticatedUpgradeCallbackRoute
  '/_authenticated/profile/': typeof AuthenticatedProfileIndexRoute
  '/api/public/novahub/webhook': typeof ApiPublicNovahubWebhookRoute
  '/api/public/paystack/webhook': typeof ApiPublicPaystackWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/admin/nova-hub'
    | '/admin/payments'
    | '/profile/about'
    | '/profile/feedback'
    | '/profile/personal'
    | '/profile/privacy'
    | '/profile/support'
    | '/upgrade/callback'
    | '/profile/'
    | '/api/public/novahub/webhook'
    | '/api/public/paystack/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/reset-password'
    | '/'
    | '/admin/nova-hub'
    | '/admin/payments'
    | '/profile/about'
    | '/profile/feedback'
    | '/profile/personal'
    | '/profile/privacy'
    | '/profile/support'
    | '/upgrade/callback'
    | '/profile'
    | '/api/public/novahub/webhook'
    | '/api/public/paystack/webhook'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/'
    | '/_authenticated/admin/nova-hub'
    | '/_authenticated/admin/payments'
    | '/_authenticated/profile/about'
    | '/_authenticated/profile/feedback'
    | '/_authenticated/profile/personal'
    | '/_authenticated/profile/privacy'
    | '/_authenticated/profile/support'
    | '/_authenticated/upgrade/callback'
    | '/_authenticated/profile/'
    | '/api/public/novahub/webhook'
    | '/api/public/paystack/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicNovahubWebhookRoute: typeof ApiPublicNovahubWebhookRoute
  ApiPublicPaystackWebhookRoute: typeof ApiPublicPaystackWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile/': {
      id: '/_authenticated/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof AuthenticatedProfileIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/upgrade/callback': {
      id: '/_authenticated/upgrade/callback'
      path: '/upgrade/callback'
      fullPath: '/upgrade/callback'
      preLoaderRoute: typeof AuthenticatedUpgradeCallbackRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile/support': {
      id: '/_authenticated/profile/support'
      path: '/profile/support'
      fullPath: '/profile/support'
      preLoaderRoute: typeof AuthenticatedProfileSupportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile/privacy': {
      id: '/_authenticated/profile/privacy'
      path: '/profile/privacy'
      fullPath: '/profile/privacy'
      preLoaderRoute: typeof AuthenticatedProfilePrivacyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile/personal': {
      id: '/_authenticated/profile/personal'
      path: '/profile/personal'
      fullPath: '/profile/personal'
      preLoaderRoute: typeof AuthenticatedProfilePersonalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile/feedback': {
      id: '/_authenticated/profile/feedback'
      path: '/profile/feedback'
      fullPath: '/profile/feedback'
      preLoaderRoute: typeof AuthenticatedProfileFeedbackRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile/about': {
      id: '/_authenticated/profile/about'
      path: '/profile/about'
      fullPath: '/profile/about'
      preLoaderRoute: typeof AuthenticatedProfileAboutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/payments': {
      id: '/_authenticated/admin/payments'
      path: '/admin/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/nova-hub': {
      id: '/_authenticated/admin/nova-hub'
      path: '/admin/nova-hub'
      fullPath: '/admin/nova-hub'
      preLoaderRoute: typeof AuthenticatedAdminNovaHubRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/paystack/webhook': {
      id: '/api/public/paystack/webhook'
      path: '/api/public/paystack/webhook'
      fullPath: '/api/public/paystack/webhook'
      preLoaderRoute: typeof ApiPublicPaystackWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/novahub/webhook': {
      id: '/api/public/novahub/webhook'
      path: '/api/public/novahub/webhook'
      fullPath: '/api/public/novahub/webhook'
      preLoaderRoute: typeof ApiPublicNovahubWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdminNovaHubRoute: typeof AuthenticatedAdminNovaHubRoute
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRoute
  AuthenticatedProfileAboutRoute: typeof AuthenticatedProfileAboutRoute
  AuthenticatedProfileFeedbackRoute: typeof AuthenticatedProfileFeedbackRoute
  AuthenticatedProfilePersonalRoute: typeof AuthenticatedProfilePersonalRoute
  AuthenticatedProfilePrivacyRoute: typeof AuthenticatedProfilePrivacyRoute
  AuthenticatedProfileSupportRoute: typeof AuthenticatedProfileSupportRoute
  AuthenticatedUpgradeCallbackRoute: typeof AuthenticatedUpgradeCallbackRoute
  AuthenticatedProfileIndexRoute: typeof AuthenticatedProfileIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdminNovaHubRoute: AuthenticatedAdminNovaHubRoute,
  AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRoute,
  AuthenticatedProfileAboutRoute: AuthenticatedProfileAboutRoute,
  AuthenticatedProfileFeedbackRoute: AuthenticatedProfileFeedbackRoute,
  AuthenticatedProfilePersonalRoute: AuthenticatedProfilePersonalRoute,
  AuthenticatedProfilePrivacyRoute: AuthenticatedProfilePrivacyRoute,
  AuthenticatedProfileSupportRoute: AuthenticatedProfileSupportRoute,
  AuthenticatedUpgradeCallbackRoute: AuthenticatedUpgradeCallbackRoute,
  AuthenticatedProfileIndexRoute: AuthenticatedProfileIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicNovahubWebhookRoute: ApiPublicNovahubWebhookRoute,
  ApiPublicPaystackWebhookRoute: ApiPublicPaystackWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
